# Generated by Django 4.1.1 on 2022-09-20 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tidanapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='First_name',
            new_name='Full_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='Last_name',
        ),
    ]
